using Microsoft.Win32;
using System.Diagnostics;
using System.Diagnostics.Eventing.Reader;
using System.Management;
using System.Text;

namespace PawnIO
{
    /// <summary>
    /// Aggregates Intel Raptor Lake health diagnostics: WHEA error monitoring,
    /// VID voltage telemetry, power limit readback, and generates exportable
    /// "Proof of Instability" reports for Intel RMA or retailer warranty claims.
    /// </summary>
    public static class IntelRaptorLakeDiag
    {
        public enum DegradationRisk { None, Low, Moderate, High, Critical }

        /// <summary>
        /// Queries the Windows Event Log for WHEA (Windows Hardware Error Architecture)
        /// logger events in the last 24 hours. Non-zero counts on a Raptor Lake system
        /// are a strong indicator of silicon degradation.
        /// </summary>
        public static int GetWheaErrorCount(int hours = 24)
        {
            try
            {
                string query = $"*[System[Provider[@Name='Microsoft-Windows-WHEA-Logger'] " +
                               $"and TimeCreated[timediff(@SystemTime) <= {hours * 3600 * 1000L}]]]";

                using var reader = new EventLogReader(new EventLogQuery("System", PathType.LogName, query));
                int count = 0;
                while (reader.ReadEvent() != null) count++;
                return count;
            }
            catch (Exception ex)
            {
                Logger.WriteLine("WHEA event query failed: " + ex.Message);
                return -1; // Indicates query failure, not zero errors
            }
        }

        /// <summary>
        /// Reads the current VID voltage from IA32_PERF_STATUS via an existing IntelMsr instance.
        /// Returns null if PawnIO is unavailable or the read fails.
        /// </summary>
        public static float? GetCurrentVid(IntelMsr? msr)
        {
            if (msr == null || !msr.IsInitialized) return null;

            try
            {
                return msr.GetCoreVoltage();
            }
            catch (Exception ex)
            {
                Logger.WriteLine("VID read failed: " + ex.Message);
                return null;
            }
        }

        /// <summary>
        /// Assesses the overall degradation risk based on available telemetry.
        /// </summary>
        public static DegradationRisk AssessRisk(int wheaCount, float? currentVid)
        {
            if (!IntelMicrocodeCheck.IsRaptorLake)
                return DegradationRisk.None;

            // WHEA errors are the strongest degradation signal
            if (wheaCount > 10) return DegradationRisk.Critical;
            if (wheaCount > 3) return DegradationRisk.High;

            // Elevated VID during idle/light load suggests aggressive voltage requests
            if (currentVid.HasValue && currentVid.Value > 1.50f)
                return DegradationRisk.High;
            if (currentVid.HasValue && currentVid.Value > 1.40f)
                return DegradationRisk.Moderate;

            if (wheaCount > 0) return DegradationRisk.Moderate;

            if (!IntelMicrocodeCheck.IsVulnerable)
                return DegradationRisk.None;

            // Vulnerable microcode but no symptoms yet
            return DegradationRisk.Low;
        }

        /// <summary>
        /// Generates a comprehensive diagnostic report suitable for Intel RMA claims
        /// or Austrian Gewährleistung retailer disputes.
        /// </summary>
        public static string GenerateReport(IntelMsr? msr = null)
        {
            var sb = new StringBuilder();
            sb.AppendLine("═══════════════════════════════════════════════════════════════");
            sb.AppendLine("  Intel Raptor Lake Vmin Shift Instability — Diagnostic Report");
            sb.AppendLine("  Generated by G-Helper");
            sb.AppendLine("═══════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine($"Report Date:      {DateTime.Now:yyyy-MM-dd HH:mm:ss zzz}");
            sb.AppendLine();

            // System Information
            sb.AppendLine("── System Information ──────────────────────────────────────────");
            sb.AppendLine($"CPU Name:         {CpuInfo.Name}");
            sb.AppendLine($"CPU Identifier:   {CpuInfo.Caption}");
            sb.AppendLine($"CPUID:            0x{IntelMicrocodeCheck.CpuIdValue:X}");
            sb.AppendLine($"Raptor Lake:      {IntelMicrocodeCheck.IsRaptorLake}");
            sb.AppendLine($"System Model:     {GetSystemModel()}");
            sb.AppendLine($"BIOS Version:     {GetBiosVersion()}");
            sb.AppendLine($"OS Build:         {Environment.OSVersion.VersionString}");
            sb.AppendLine();

            // Microcode Status
            sb.AppendLine("── Microcode Status ───────────────────────────────────────────");
            sb.AppendLine($"Registry Rev:     0x{IntelMicrocodeCheck.MicrocodeRevision:X}");

            uint? msrRev = msr != null ? IntelMicrocodeCheck.ReadMicrocodeFromMsr(msr) : null;
            if (msrRev.HasValue)
                sb.AppendLine($"MSR Rev:          0x{msrRev.Value:X}");

            sb.AppendLine($"Min Safe Rev:     0x{IntelMicrocodeCheck.MinimumSafeRevision:X}");
            sb.AppendLine($"Status:           {IntelMicrocodeCheck.StatusSummary}");
            sb.AppendLine();

            // WHEA Error Analysis
            sb.AppendLine("── WHEA Error Analysis ────────────────────────────────────────");
            int whea24h = GetWheaErrorCount(24);
            int whea7d = GetWheaErrorCount(168);
            int whea30d = GetWheaErrorCount(720);
            sb.AppendLine($"Last 24 hours:    {(whea24h >= 0 ? whea24h.ToString() : "Query failed")}");
            sb.AppendLine($"Last 7 days:      {(whea7d >= 0 ? whea7d.ToString() : "Query failed")}");
            sb.AppendLine($"Last 30 days:     {(whea30d >= 0 ? whea30d.ToString() : "Query failed")}");
            sb.AppendLine();

            // Voltage Telemetry
            sb.AppendLine("── Voltage Telemetry (VID from IA32_PERF_STATUS) ────────────");
            float? vid = GetCurrentVid(msr);
            if (vid.HasValue)
            {
                sb.AppendLine($"Current VID:      {vid.Value:F3}V");
                if (vid.Value > 1.50f)
                    sb.AppendLine($"  ⚠ WARNING: VID exceeds 1.50V — indicates aggressive voltage requests");
                else if (vid.Value > 1.40f)
                    sb.AppendLine($"  ⚠ CAUTION: VID elevated above 1.40V");
            }
            else
            {
                sb.AppendLine($"Current VID:      Unavailable (PawnIO driver not loaded)");
            }
            sb.AppendLine();

            // Intel Default Limits
            sb.AppendLine("── Power Limit Configuration ──────────────────────────────────");
            var limits = IntelMicrocodeCheck.GetIntelDefaultLimitsForCpu();
            if (limits.HasValue)
                sb.AppendLine($"Intel Spec:       PL1={limits.Value.PL1}W, PL2={limits.Value.PL2}W");
            else
                sb.AppendLine($"Intel Spec:       SKU not in limits table");
            sb.AppendLine();

            // Risk Assessment
            DegradationRisk risk = AssessRisk(Math.Max(whea24h, 0), vid);
            sb.AppendLine("── Risk Assessment ────────────────────────────────────────────");
            sb.AppendLine($"Degradation Risk: {risk}");
            sb.AppendLine();

            switch (risk)
            {
                case DegradationRisk.Critical:
                case DegradationRisk.High:
                    sb.AppendLine("RECOMMENDATION: This processor shows strong indicators of Vmin Shift");
                    sb.AppendLine("degradation. Physical hardware replacement is the only remedy.");
                    sb.AppendLine("Contact Intel Customer Support or your retailer for RMA/warranty claim.");
                    sb.AppendLine("Intel has extended warranty to 5 years for affected 13th/14th Gen CPUs.");
                    break;
                case DegradationRisk.Moderate:
                    sb.AppendLine("RECOMMENDATION: Some degradation indicators detected. Update BIOS to");
                    sb.AppendLine("ensure microcode 0x12B is applied. Monitor WHEA errors over the next");
                    sb.AppendLine("weeks. If errors increase, initiate an RMA claim.");
                    break;
                case DegradationRisk.Low:
                    sb.AppendLine("RECOMMENDATION: CPU running vulnerable microcode but no degradation");
                    sb.AppendLine("symptoms detected yet. Update BIOS immediately to apply microcode 0x12B");
                    sb.AppendLine("to prevent future damage.");
                    break;
                default:
                    sb.AppendLine("No degradation indicators detected.");
                    break;
            }

            sb.AppendLine();
            sb.AppendLine("═══════════════════════════════════════════════════════════════");
            sb.AppendLine("  This report may be attached to Intel RMA claims (provide ATPO/FPO)");
            sb.AppendLine("  or retailer Gewährleistung disputes under Austrian VGG § 11.");
            sb.AppendLine("═══════════════════════════════════════════════════════════════");

            return sb.ToString();
        }

        private static string GetSystemModel()
        {
            try
            {
                return AppConfig.GetModel();
            }
            catch
            {
                return "Unknown";
            }
        }

        private static string GetBiosVersion()
        {
            try
            {
                using var key = Registry.LocalMachine.OpenSubKey(@"HARDWARE\DESCRIPTION\System\BIOS");
                string? version = key?.GetValue("BIOSVersion")?.ToString();
                string? date = key?.GetValue("BIOSReleaseDate")?.ToString();
                return $"{version ?? "Unknown"} ({date ?? "Unknown"})";
            }
            catch
            {
                return "Unknown";
            }
        }
    }
}
