name: Bug Report
description: Something isn't working correctly
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. The more information you provide, the easier it will be for me to fix it!
  - type: checkboxes
    id: rules
    attributes:
      label: Rules
      options:
        - label: I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
          required: true
        - label: I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.
          required: true
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What's wrong?
      description: Provide detailed description of what is wrong or does not work as expected.
      placeholder: Provide detailed description of what is wrong or does not work as expected.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the bug?
      description: Describe how to reproduce the behavior. Be as specific as possible and provide as many details as possible.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      placeholder: Please drag and drop complete log file from ``%APPDATA%\GHelper\log.txt``
      description: Please drag and drop complete log file from ``%APPDATA%\GHelper\log.txt``
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device and Model
      description: Which laptop do you use?
      placeholder: e.g. Asus Zephyrus G14 GA404RK
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information. 
      description: If applicable, add screenshots or other relevant information to help explain your problem.
  - type: dropdown
    id: armoury
    attributes:
      label: Armoury Crate
      description: Do you have Armoury Crate installed?
      options:
        - Uninstalled
        - Installed
        - Never installed
      default: 0   
  - type: input
    id: asus
    attributes:
      label: Asus Services
      description: How many Asus services do you have running (check ``Extra`` section in G-Helper)?
      placeholder: e.g. None
  - type: input
    id: version
    attributes:
      label: Version
      description: G-Helper version?
      placeholder: e.g. 0.146
  - type: input
    id: os
    attributes:
      label: OS
      description: Which operating system do you use?
      placeholder: e.g. Windows 11 21H2     
          
