name: Feature request
description: Suggest an idea for this project
body:
  - type: checkboxes
    id: rules
    attributes:
      label: Rules
      options:
        - label: I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
          required: true
        - label: I understand that, if insufficient information will be provided, my issue will be closed without an answer.
          required: true
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: input
    id: device
    attributes:
      label: Device and Model
      description: Which laptop do you use?
      placeholder: e.g. Asus Zephyrus G14 GA404RK
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information. 
      placeholder: If applicable, add screenshots or other relevant information          
