title: G-Helper
description: G-Helper is a lightweight, open-source Armoury Crate alternative for Asus ROG Zephyrus G14, G15, G16, M16, Flow X13, X16, Z13, TUF, Strix, Scar, Vivobook, Zenbook, ProArt, ROG Ally and other Asus laptops.
plugins:
  - jemoji
