//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHelper.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t connect to ASUS ACPI. Application can&apos;t function without it. Try to install Asus System Control Interface 的本地化字符串。
        /// </summary>
        internal static string ACPIError {
            get {
                return ResourceManager.GetString("ACPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looks like GPU is in heavy use, disable it? 的本地化字符串。
        /// </summary>
        internal static string AlertDGPU {
            get {
                return ResourceManager.GetString("AlertDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eco Mode 的本地化字符串。
        /// </summary>
        internal static string AlertDGPUTitle {
            get {
                return ResourceManager.GetString("AlertDGPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switching off Ultimate Mode requires restart 的本地化字符串。
        /// </summary>
        internal static string AlertUltimateOff {
            get {
                return ResourceManager.GetString("AlertUltimateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ultimate Mode requires restart 的本地化字符串。
        /// </summary>
        internal static string AlertUltimateOn {
            get {
                return ResourceManager.GetString("AlertUltimateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot now? 的本地化字符串。
        /// </summary>
        internal static string AlertUltimateTitle {
            get {
                return ResourceManager.GetString("AlertUltimateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animation Speed 的本地化字符串。
        /// </summary>
        internal static string AnimationSpeed {
            get {
                return ResourceManager.GetString("AnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anime Matrix 的本地化字符串。
        /// </summary>
        internal static string AnimeMatrix {
            get {
                return ResourceManager.GetString("AnimeMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App already running 的本地化字符串。
        /// </summary>
        internal static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G-Helper is already running. Check system tray for an icon. 的本地化字符串。
        /// </summary>
        internal static string AppAlreadyRunningText {
            get {
                return ResourceManager.GetString("AppAlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Custom Fan Curve 的本地化字符串。
        /// </summary>
        internal static string ApplyFanCurve {
            get {
                return ResourceManager.GetString("ApplyFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Power Limits 的本地化字符串。
        /// </summary>
        internal static string ApplyPowerLimits {
            get {
                return ResourceManager.GetString("ApplyPowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breathe 的本地化字符串。
        /// </summary>
        internal static string AuraBreathe {
            get {
                return ResourceManager.GetString("AuraBreathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Cycle 的本地化字符串。
        /// </summary>
        internal static string AuraColorCycle {
            get {
                return ResourceManager.GetString("AuraColorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        internal static string AuraFast {
            get {
                return ResourceManager.GetString("AuraFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string AuraNormal {
            get {
                return ResourceManager.GetString("AuraNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow 的本地化字符串。
        /// </summary>
        internal static string AuraRainbow {
            get {
                return ResourceManager.GetString("AuraRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow 的本地化字符串。
        /// </summary>
        internal static string AuraSlow {
            get {
                return ResourceManager.GetString("AuraSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        internal static string AuraStatic {
            get {
                return ResourceManager.GetString("AuraStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strobe 的本地化字符串。
        /// </summary>
        internal static string AuraStrobe {
            get {
                return ResourceManager.GetString("AuraStrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets 60Hz to save battery, and back when plugged 的本地化字符串。
        /// </summary>
        internal static string AutoRefreshTooltip {
            get {
                return ResourceManager.GetString("AutoRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awake 的本地化字符串。
        /// </summary>
        internal static string Awake {
            get {
                return ResourceManager.GetString("Awake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balanced 的本地化字符串。
        /// </summary>
        internal static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Charge Limit 的本地化字符串。
        /// </summary>
        internal static string BatteryChargeLimit {
            get {
                return ResourceManager.GetString("BatteryChargeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boot 的本地化字符串。
        /// </summary>
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness 的本地化字符串。
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Boost 的本地化字符串。
        /// </summary>
        internal static string CPUBoost {
            get {
                return ResourceManager.GetString("CPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable screen overdrive 的本地化字符串。
        /// </summary>
        internal static string DisableOverdrive {
            get {
                return ResourceManager.GetString("DisableOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discharging 的本地化字符串。
        /// </summary>
        internal static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Update 的本地化字符串。
        /// </summary>
        internal static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables dGPU for battery savings 的本地化字符串。
        /// </summary>
        internal static string EcoGPUTooltip {
            get {
                return ResourceManager.GetString("EcoGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eco 的本地化字符串。
        /// </summary>
        internal static string EcoMode {
            get {
                return ResourceManager.GetString("EcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra 的本地化字符串。
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Settings 的本地化字符串。
        /// </summary>
        internal static string ExtraSettings {
            get {
                return ResourceManager.GetString("ExtraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Factory Defaults 的本地化字符串。
        /// </summary>
        internal static string FactoryDefaults {
            get {
                return ResourceManager.GetString("FactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan Curves 的本地化字符串。
        /// </summary>
        internal static string FanCurves {
            get {
                return ResourceManager.GetString("FanCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Fan Profile 的本地化字符串。
        /// </summary>
        internal static string FanProfileCPU {
            get {
                return ResourceManager.GetString("FanProfileCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Fan Profile 的本地化字符串。
        /// </summary>
        internal static string FanProfileGPU {
            get {
                return ResourceManager.GetString("FanProfileGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mid Fan Profile 的本地化字符串。
        /// </summary>
        internal static string FanProfileMid {
            get {
                return ResourceManager.GetString("FanProfileMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan Profiles 的本地化字符串。
        /// </summary>
        internal static string FanProfiles {
            get {
                return ResourceManager.GetString("FanProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fans and Power 的本地化字符串。
        /// </summary>
        internal static string FansAndPower {
            get {
                return ResourceManager.GetString("FansAndPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fans + Power 的本地化字符串。
        /// </summary>
        internal static string FansPower {
            get {
                return ResourceManager.GetString("FansPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing 的本地化字符串。
        /// </summary>
        internal static string GPUChanging {
            get {
                return ResourceManager.GetString("GPUChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Mode 的本地化字符串。
        /// </summary>
        internal static string GPUMode {
            get {
                return ResourceManager.GetString("GPUMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iGPU only 的本地化字符串。
        /// </summary>
        internal static string GPUModeEco {
            get {
                return ResourceManager.GetString("GPUModeEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iGPU + dGPU 的本地化字符串。
        /// </summary>
        internal static string GPUModeStandard {
            get {
                return ResourceManager.GetString("GPUModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dGPU exclusive 的本地化字符串。
        /// </summary>
        internal static string GPUModeUltimate {
            get {
                return ResourceManager.GetString("GPUModeUltimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Bindings 的本地化字符串。
        /// </summary>
        internal static string KeyBindings {
            get {
                return ResourceManager.GetString("KeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard 的本地化字符串。
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lower backlight brightness on battery and back when plugged 的本地化字符串。
        /// </summary>
        internal static string KeyboardAuto {
            get {
                return ResourceManager.GetString("KeyboardAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard Backlight 的本地化字符串。
        /// </summary>
        internal static string KeyboardBacklight {
            get {
                return ResourceManager.GetString("KeyboardBacklight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laptop Keyboard 的本地化字符串。
        /// </summary>
        internal static string LaptopKeyboard {
            get {
                return ResourceManager.GetString("LaptopKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laptop Screen 的本地化字符串。
        /// </summary>
        internal static string LaptopScreen {
            get {
                return ResourceManager.GetString("LaptopScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary Banner 的本地化字符串。
        /// </summary>
        internal static string MatrixBanner {
            get {
                return ResourceManager.GetString("MatrixBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bright 的本地化字符串。
        /// </summary>
        internal static string MatrixBright {
            get {
                return ResourceManager.GetString("MatrixBright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clock 的本地化字符串。
        /// </summary>
        internal static string MatrixClock {
            get {
                return ResourceManager.GetString("MatrixClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dim 的本地化字符串。
        /// </summary>
        internal static string MatrixDim {
            get {
                return ResourceManager.GetString("MatrixDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rog Logo 的本地化字符串。
        /// </summary>
        internal static string MatrixLogo {
            get {
                return ResourceManager.GetString("MatrixLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        internal static string MatrixMedium {
            get {
                return ResourceManager.GetString("MatrixMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string MatrixOff {
            get {
                return ResourceManager.GetString("MatrixOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture 的本地化字符串。
        /// </summary>
        internal static string MatrixPicture {
            get {
                return ResourceManager.GetString("MatrixPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max refresh rate for lower latency 的本地化字符串。
        /// </summary>
        internal static string MaxRefreshTooltip {
            get {
                return ResourceManager.GetString("MaxRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 60Hz refresh rate to save battery 的本地化字符串。
        /// </summary>
        internal static string MinRefreshTooltip {
            get {
                return ResourceManager.GetString("MinRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multizone 的本地化字符串。
        /// </summary>
        internal static string Multizone {
            get {
                return ResourceManager.GetString("Multizone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open G-Helper window 的本地化字符串。
        /// </summary>
        internal static string OpenGHelper {
            get {
                return ResourceManager.GetString("OpenGHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimized 的本地化字符串。
        /// </summary>
        internal static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to Eco on battery and to Standard when plugged 的本地化字符串。
        /// </summary>
        internal static string OptimizedGPUTooltip {
            get {
                return ResourceManager.GetString("OptimizedGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overdrive 的本地化字符串。
        /// </summary>
        internal static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance Mode 的本地化字符串。
        /// </summary>
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture / Gif 的本地化字符串。
        /// </summary>
        internal static string PictureGif {
            get {
                return ResourceManager.GetString("PictureGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play / Pause 的本地化字符串。
        /// </summary>
        internal static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Limits (PPT) 的本地化字符串。
        /// </summary>
        internal static string PowerLimits {
            get {
                return ResourceManager.GetString("PowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Limits (PPT) is experimental feature. Use carefully and on your own risk! 的本地化字符串。
        /// </summary>
        internal static string PPTExperimental {
            get {
                return ResourceManager.GetString("PPTExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintScreen 的本地化字符串。
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPM 的本地化字符串。
        /// </summary>
        internal static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run on Startup 的本地化字符串。
        /// </summary>
        internal static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown 的本地化字符串。
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silent 的本地化字符串。
        /// </summary>
        internal static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sleep 的本地化字符串。
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables dGPU for standard use 的本地化字符串。
        /// </summary>
        internal static string StandardGPUTooltip {
            get {
                return ResourceManager.GetString("StandardGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string StandardMode {
            get {
                return ResourceManager.GetString("StandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup Error 的本地化字符串。
        /// </summary>
        internal static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Aura 的本地化字符串。
        /// </summary>
        internal static string ToggleAura {
            get {
                return ResourceManager.GetString("ToggleAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turbo 的本地化字符串。
        /// </summary>
        internal static string Turbo {
            get {
                return ResourceManager.GetString("Turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turned off 的本地化字符串。
        /// </summary>
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off on battery 的本地化字符串。
        /// </summary>
        internal static string TurnOffOnBattery {
            get {
                return ResourceManager.GetString("TurnOffOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routes laptop screen to dGPU, maximizing FPS 的本地化字符串。
        /// </summary>
        internal static string UltimateGPUTooltip {
            get {
                return ResourceManager.GetString("UltimateGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ultimate 的本地化字符串。
        /// </summary>
        internal static string UltimateMode {
            get {
                return ResourceManager.GetString("UltimateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Mute 的本地化字符串。
        /// </summary>
        internal static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep app window always on top 的本地化字符串。
        /// </summary>
        internal static string WindowTop {
            get {
                return ResourceManager.GetString("WindowTop", resourceCulture);
            }
        }
    }
}
