//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GHelper.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Acceleration 的本地化字符串。
        /// </summary>
        internal static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t connect to ASUS ACPI. Application can&apos;t function without it. Try to install Asus System Control Interface 的本地化字符串。
        /// </summary>
        internal static string ACPIError {
            get {
                return ResourceManager.GetString("ACPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart your device to apply changes 的本地化字符串。
        /// </summary>
        internal static string AlertAPUMemoryRestart {
            get {
                return ResourceManager.GetString("AlertAPUMemoryRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart now? 的本地化字符串。
        /// </summary>
        internal static string AlertAPUMemoryRestartTitle {
            get {
                return ResourceManager.GetString("AlertAPUMemoryRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looks like GPU is in heavy use, disable it? 的本地化字符串。
        /// </summary>
        internal static string AlertDGPU {
            get {
                return ResourceManager.GetString("AlertDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eco Mode 的本地化字符串。
        /// </summary>
        internal static string AlertDGPUTitle {
            get {
                return ResourceManager.GetString("AlertDGPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switching off Ultimate Mode requires restart 的本地化字符串。
        /// </summary>
        internal static string AlertUltimateOff {
            get {
                return ResourceManager.GetString("AlertUltimateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ultimate Mode requires restart 的本地化字符串。
        /// </summary>
        internal static string AlertUltimateOn {
            get {
                return ResourceManager.GetString("AlertUltimateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reboot now? 的本地化字符串。
        /// </summary>
        internal static string AlertUltimateTitle {
            get {
                return ResourceManager.GetString("AlertUltimateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ally Controller 的本地化字符串。
        /// </summary>
        internal static string AllyController {
            get {
                return ResourceManager.GetString("AllyController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animation Speed 的本地化字符串。
        /// </summary>
        internal static string AnimationSpeed {
            get {
                return ResourceManager.GetString("AnimationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anime Matrix 的本地化字符串。
        /// </summary>
        internal static string AnimeMatrix {
            get {
                return ResourceManager.GetString("AnimeMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App already running 的本地化字符串。
        /// </summary>
        internal static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G-Helper is already running. Check system tray for an icon. 的本地化字符串。
        /// </summary>
        internal static string AppAlreadyRunningText {
            get {
                return ResourceManager.GetString("AppAlreadyRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Custom Fan Curve 的本地化字符串。
        /// </summary>
        internal static string ApplyFanCurve {
            get {
                return ResourceManager.GetString("ApplyFanCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Power Limits 的本地化字符串。
        /// </summary>
        internal static string ApplyPowerLimits {
            get {
                return ResourceManager.GetString("ApplyPowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto adjust Windows Power Modes 的本地化字符串。
        /// </summary>
        internal static string ApplyWindowsPowerPlan {
            get {
                return ResourceManager.GetString("ApplyWindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Assigned to GPU 的本地化字符串。
        /// </summary>
        internal static string APUMemory {
            get {
                return ResourceManager.GetString("APUMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asus Services Running 的本地化字符串。
        /// </summary>
        internal static string AsusServicesRunning {
            get {
                return ResourceManager.GetString("AsusServicesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery State 的本地化字符串。
        /// </summary>
        internal static string AuraBatteryState {
            get {
                return ResourceManager.GetString("AuraBatteryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breathe 的本地化字符串。
        /// </summary>
        internal static string AuraBreathe {
            get {
                return ResourceManager.GetString("AuraBreathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clockwise 的本地化字符串。
        /// </summary>
        internal static string AuraClockwise {
            get {
                return ResourceManager.GetString("AuraClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Cycle 的本地化字符串。
        /// </summary>
        internal static string AuraColorCycle {
            get {
                return ResourceManager.GetString("AuraColorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comet 的本地化字符串。
        /// </summary>
        internal static string AuraComet {
            get {
                return ResourceManager.GetString("AuraComet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Counterclockwise 的本地化字符串。
        /// </summary>
        internal static string AuraCounterClockwise {
            get {
                return ResourceManager.GetString("AuraCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast 的本地化字符串。
        /// </summary>
        internal static string AuraFast {
            get {
                return ResourceManager.GetString("AuraFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lighting Mode 的本地化字符串。
        /// </summary>
        internal static string AuraLightingMode {
            get {
                return ResourceManager.GetString("AuraLightingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        internal static string AuraNormal {
            get {
                return ResourceManager.GetString("AuraNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rainbow 的本地化字符串。
        /// </summary>
        internal static string AuraRainbow {
            get {
                return ResourceManager.GetString("AuraRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random 的本地化字符串。
        /// </summary>
        internal static string AuraRandomColor {
            get {
                return ResourceManager.GetString("AuraRandomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 React 的本地化字符串。
        /// </summary>
        internal static string AuraReact {
            get {
                return ResourceManager.GetString("AuraReact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow 的本地化字符串。
        /// </summary>
        internal static string AuraSlow {
            get {
                return ResourceManager.GetString("AuraSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        internal static string AuraStatic {
            get {
                return ResourceManager.GetString("AuraStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strobe 的本地化字符串。
        /// </summary>
        internal static string AuraStrobe {
            get {
                return ResourceManager.GetString("AuraStrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string AuraZoneAll {
            get {
                return ResourceManager.GetString("AuraZoneAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock 的本地化字符串。
        /// </summary>
        internal static string AuraZoneDock {
            get {
                return ResourceManager.GetString("AuraZoneDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo 的本地化字符串。
        /// </summary>
        internal static string AuraZoneLogo {
            get {
                return ResourceManager.GetString("AuraZoneLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scrollwheel 的本地化字符串。
        /// </summary>
        internal static string AuraZoneScroll {
            get {
                return ResourceManager.GetString("AuraZoneScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underglow 的本地化字符串。
        /// </summary>
        internal static string AuraZoneUnderglow {
            get {
                return ResourceManager.GetString("AuraZoneUnderglow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Apply 的本地化字符串。
        /// </summary>
        internal static string AutoApply {
            get {
                return ResourceManager.GetString("AutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets 60Hz to save battery, and back when plugged 的本地化字符串。
        /// </summary>
        internal static string AutoRefreshTooltip {
            get {
                return ResourceManager.GetString("AutoRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awake 的本地化字符串。
        /// </summary>
        internal static string Awake {
            get {
                return ResourceManager.GetString("Awake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        internal static string BacklightLow {
            get {
                return ResourceManager.GetString("BacklightLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max 的本地化字符串。
        /// </summary>
        internal static string BacklightMax {
            get {
                return ResourceManager.GetString("BacklightMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mid 的本地化字符串。
        /// </summary>
        internal static string BacklightMid {
            get {
                return ResourceManager.GetString("BacklightMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string BacklightOff {
            get {
                return ResourceManager.GetString("BacklightOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout plugged / on battery (0 - ON) 的本地化字符串。
        /// </summary>
        internal static string BacklightTimeout {
            get {
                return ResourceManager.GetString("BacklightTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backlight Timeout when on battery 的本地化字符串。
        /// </summary>
        internal static string BacklightTimeoutBattery {
            get {
                return ResourceManager.GetString("BacklightTimeoutBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backlight Timeout when plugged 的本地化字符串。
        /// </summary>
        internal static string BacklightTimeoutPlugged {
            get {
                return ResourceManager.GetString("BacklightTimeoutPlugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balanced 的本地化字符串。
        /// </summary>
        internal static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charge 的本地化字符串。
        /// </summary>
        internal static string BatteryCharge {
            get {
                return ResourceManager.GetString("BatteryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Charge Limit 的本地化字符串。
        /// </summary>
        internal static string BatteryChargeLimit {
            get {
                return ResourceManager.GetString("BatteryChargeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Health 的本地化字符串。
        /// </summary>
        internal static string BatteryHealth {
            get {
                return ResourceManager.GetString("BatteryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One time charge to 100% 的本地化字符串。
        /// </summary>
        internal static string BatteryLimitFull {
            get {
                return ResourceManager.GetString("BatteryLimitFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding 的本地化字符串。
        /// </summary>
        internal static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary 的本地化字符串。
        /// </summary>
        internal static string BindingPrimary {
            get {
                return ResourceManager.GetString("BindingPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary 的本地化字符串。
        /// </summary>
        internal static string BindingSecondary {
            get {
                return ResourceManager.GetString("BindingSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BIOS and Driver Updates 的本地化字符串。
        /// </summary>
        internal static string BiosAndDriverUpdates {
            get {
                return ResourceManager.GetString("BiosAndDriverUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boot 的本地化字符串。
        /// </summary>
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boot Sound 的本地化字符串。
        /// </summary>
        internal static string BootSound {
            get {
                return ResourceManager.GetString("BootSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness 的本地化字符串。
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness Down 的本地化字符串。
        /// </summary>
        internal static string BrightnessDown {
            get {
                return ResourceManager.GetString("BrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brightness Up 的本地化字符串。
        /// </summary>
        internal static string BrightnessUp {
            get {
                return ResourceManager.GetString("BrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black and white tray icon 的本地化字符串。
        /// </summary>
        internal static string BWTrayIcon {
            get {
                return ResourceManager.GetString("BWTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibrate 的本地化字符串。
        /// </summary>
        internal static string Calibrate {
            get {
                return ResourceManager.GetString("Calibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charging 的本地化字符串。
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contrast 的本地化字符串。
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Controller 的本地化字符串。
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Boost 的本地化字符串。
        /// </summary>
        internal static string CPUBoost {
            get {
                return ResourceManager.GetString("CPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deceleration 的本地化字符串。
        /// </summary>
        internal static string Deceleration {
            get {
                return ResourceManager.GetString("Deceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Controller 的本地化字符串。
        /// </summary>
        internal static string DisableController {
            get {
                return ResourceManager.GetString("DisableController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable on lid close 的本地化字符串。
        /// </summary>
        internal static string DisableOnLidClose {
            get {
                return ResourceManager.GetString("DisableOnLidClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable screen overdrive 的本地化字符串。
        /// </summary>
        internal static string DisableOverdrive {
            get {
                return ResourceManager.GetString("DisableOverdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discharging 的本地化字符串。
        /// </summary>
        internal static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Color Profiles 的本地化字符串。
        /// </summary>
        internal static string DownloadColorProfiles {
            get {
                return ResourceManager.GetString("DownloadColorProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drivers and Software 的本地化字符串。
        /// </summary>
        internal static string DriverAndSoftware {
            get {
                return ResourceManager.GetString("DriverAndSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables dGPU to save battery 的本地化字符串。
        /// </summary>
        internal static string EcoGPUTooltip {
            get {
                return ResourceManager.GetString("EcoGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eco 的本地化字符串。
        /// </summary>
        internal static string EcoMode {
            get {
                return ResourceManager.GetString("EcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable GPU on shutdown (prevents issue with Eco mode) 的本地化字符串。
        /// </summary>
        internal static string EnableGPUOnShutdown {
            get {
                return ResourceManager.GetString("EnableGPUOnShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabling the dGPU by going into Eco mode while Display Mode in NVIDIA Control Panel is not set to Optimus might cause problems with brightness controls until after the next reboot. 
        ///
        ///Do you still want to continue? 的本地化字符串。
        /// </summary>
        internal static string EnableOptimusText {
            get {
                return ResourceManager.GetString("EnableOptimusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NVIDIA Display Mode is not set to Optimus 的本地化字符串。
        /// </summary>
        internal static string EnableOptimusTitle {
            get {
                return ResourceManager.GetString("EnableOptimusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Energy Settings 的本地化字符串。
        /// </summary>
        internal static string EnergySettings {
            get {
                return ResourceManager.GetString("EnergySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Profile 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra 的本地化字符串。
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Settings 的本地化字符串。
        /// </summary>
        internal static string ExtraSettings {
            get {
                return ResourceManager.GetString("ExtraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Factory Defaults 的本地化字符串。
        /// </summary>
        internal static string FactoryDefaults {
            get {
                return ResourceManager.GetString("FactoryDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan Curves 的本地化字符串。
        /// </summary>
        internal static string FanCurves {
            get {
                return ResourceManager.GetString("FanCurves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU Fan Profile 的本地化字符串。
        /// </summary>
        internal static string FanProfileCPU {
            get {
                return ResourceManager.GetString("FanProfileCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Fan Profile 的本地化字符串。
        /// </summary>
        internal static string FanProfileGPU {
            get {
                return ResourceManager.GetString("FanProfileGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mid Fan Profile 的本地化字符串。
        /// </summary>
        internal static string FanProfileMid {
            get {
                return ResourceManager.GetString("FanProfileMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan Profiles 的本地化字符串。
        /// </summary>
        internal static string FanProfiles {
            get {
                return ResourceManager.GetString("FanProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fans and Power 的本地化字符串。
        /// </summary>
        internal static string FansAndPower {
            get {
                return ResourceManager.GetString("FansAndPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fan 的本地化字符串。
        /// </summary>
        internal static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fans + Power 的本地化字符串。
        /// </summary>
        internal static string FansPower {
            get {
                return ResourceManager.GetString("FansPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flicker-free Dimming 的本地化字符串。
        /// </summary>
        internal static string FlickerFreeDimming {
            get {
                return ResourceManager.GetString("FlickerFreeDimming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Fn+F hotkeys without Fn 的本地化字符串。
        /// </summary>
        internal static string FnLock {
            get {
                return ResourceManager.GetString("FnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FN-Lock Off 的本地化字符串。
        /// </summary>
        internal static string FnLockOff {
            get {
                return ResourceManager.GetString("FnLockOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FN-Lock On 的本地化字符串。
        /// </summary>
        internal static string FnLockOn {
            get {
                return ResourceManager.GetString("FnLockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic Boost 的本地化字符串。
        /// </summary>
        internal static string GPUBoost {
            get {
                return ResourceManager.GetString("GPUBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing 的本地化字符串。
        /// </summary>
        internal static string GPUChanging {
            get {
                return ResourceManager.GetString("GPUChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Core Clock Offset 的本地化字符串。
        /// </summary>
        internal static string GPUCoreClockOffset {
            get {
                return ResourceManager.GetString("GPUCoreClockOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory Clock Offset 的本地化字符串。
        /// </summary>
        internal static string GPUMemoryClockOffset {
            get {
                return ResourceManager.GetString("GPUMemoryClockOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Mode 的本地化字符串。
        /// </summary>
        internal static string GPUMode {
            get {
                return ResourceManager.GetString("GPUMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iGPU only 的本地化字符串。
        /// </summary>
        internal static string GPUModeEco {
            get {
                return ResourceManager.GetString("GPUModeEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iGPU + dGPU 的本地化字符串。
        /// </summary>
        internal static string GPUModeStandard {
            get {
                return ResourceManager.GetString("GPUModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dGPU exclusive 的本地化字符串。
        /// </summary>
        internal static string GPUModeUltimate {
            get {
                return ResourceManager.GetString("GPUModeUltimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Power 的本地化字符串。
        /// </summary>
        internal static string GPUPower {
            get {
                return ResourceManager.GetString("GPUPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPU Settings 的本地化字符串。
        /// </summary>
        internal static string GPUSettings {
            get {
                return ResourceManager.GetString("GPUSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temperature Target 的本地化字符串。
        /// </summary>
        internal static string GPUTempTarget {
            get {
                return ResourceManager.GetString("GPUTempTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes till Hibernation in sleep on battery (0 - OFF) 的本地化字符串。
        /// </summary>
        internal static string HibernateAfter {
            get {
                return ResourceManager.GetString("HibernateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Rotation 的本地化字符串。
        /// </summary>
        internal static string ImageRotation {
            get {
                return ResourceManager.GetString("ImageRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Profile 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval Off 的本地化字符串。
        /// </summary>
        internal static string IntervalOff {
            get {
                return ResourceManager.GetString("IntervalOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval {0}s 的本地化字符串。
        /// </summary>
        internal static string IntervalSeconds {
            get {
                return ResourceManager.GetString("IntervalSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Bindings 的本地化字符串。
        /// </summary>
        internal static string KeyBindings {
            get {
                return ResourceManager.GetString("KeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyboard 的本地化字符串。
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop all apps using GPU when switching to Eco 的本地化字符串。
        /// </summary>
        internal static string KillGpuApps {
            get {
                return ResourceManager.GetString("KillGpuApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laptop Backlight 的本地化字符串。
        /// </summary>
        internal static string LaptopBacklight {
            get {
                return ResourceManager.GetString("LaptopBacklight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laptop Keyboard 的本地化字符串。
        /// </summary>
        internal static string LaptopKeyboard {
            get {
                return ResourceManager.GetString("LaptopKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laptop Screen 的本地化字符串。
        /// </summary>
        internal static string LaptopScreen {
            get {
                return ResourceManager.GetString("LaptopScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LED Status Indicators 的本地化字符串。
        /// </summary>
        internal static string LEDStatusIndicators {
            get {
                return ResourceManager.GetString("LEDStatusIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend 的本地化字符串。
        /// </summary>
        internal static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t check local version 的本地化字符串。
        /// </summary>
        internal static string LegendGray {
            get {
                return ResourceManager.GetString("LegendGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updated 的本地化字符串。
        /// </summary>
        internal static string LegendGreen {
            get {
                return ResourceManager.GetString("LegendGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Available 的本地化字符串。
        /// </summary>
        internal static string LegendRed {
            get {
                return ResourceManager.GetString("LegendRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lid 的本地化字符串。
        /// </summary>
        internal static string Lid {
            get {
                return ResourceManager.GetString("Lid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lightbar 的本地化字符串。
        /// </summary>
        internal static string Lightbar {
            get {
                return ResourceManager.GetString("Lightbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lighting 的本地化字符串。
        /// </summary>
        internal static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock Screen 的本地化字符串。
        /// </summary>
        internal static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo 的本地化字符串。
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low 的本地化字符串。
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Stick Deadzones 的本地化字符串。
        /// </summary>
        internal static string LSDeadzones {
            get {
                return ResourceManager.GetString("LSDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Trigger Deadzones 的本地化字符串。
        /// </summary>
        internal static string LTDeadzones {
            get {
                return ResourceManager.GetString("LTDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Visualizer 的本地化字符串。
        /// </summary>
        internal static string MatrixAudio {
            get {
                return ResourceManager.GetString("MatrixAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary Banner 的本地化字符串。
        /// </summary>
        internal static string MatrixBanner {
            get {
                return ResourceManager.GetString("MatrixBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bright 的本地化字符串。
        /// </summary>
        internal static string MatrixBright {
            get {
                return ResourceManager.GetString("MatrixBright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clock 的本地化字符串。
        /// </summary>
        internal static string MatrixClock {
            get {
                return ResourceManager.GetString("MatrixClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dim 的本地化字符串。
        /// </summary>
        internal static string MatrixDim {
            get {
                return ResourceManager.GetString("MatrixDim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rog Logo 的本地化字符串。
        /// </summary>
        internal static string MatrixLogo {
            get {
                return ResourceManager.GetString("MatrixLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        internal static string MatrixMedium {
            get {
                return ResourceManager.GetString("MatrixMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string MatrixOff {
            get {
                return ResourceManager.GetString("MatrixOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture 的本地化字符串。
        /// </summary>
        internal static string MatrixPicture {
            get {
                return ResourceManager.GetString("MatrixPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max refresh rate for lower latency 的本地化字符串。
        /// </summary>
        internal static string MaxRefreshTooltip {
            get {
                return ResourceManager.GetString("MaxRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 60Hz refresh rate to save battery 的本地化字符串。
        /// </summary>
        internal static string MinRefreshTooltip {
            get {
                return ResourceManager.GetString("MinRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Angle Snapping 的本地化字符串。
        /// </summary>
        internal static string MouseAngleSnapping {
            get {
                return ResourceManager.GetString("MouseAngleSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Power Off After 的本地化字符串。
        /// </summary>
        internal static string MouseAutoPowerOff {
            get {
                return ResourceManager.GetString("MouseAutoPowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button Response 的本地化字符串。
        /// </summary>
        internal static string MouseButtonResponse {
            get {
                return ResourceManager.GetString("MouseButtonResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import failed. Selected file is not a valid mouse profile or corrutpted. 的本地化字符串。
        /// </summary>
        internal static string MouseImportFailed {
            get {
                return ResourceManager.GetString("MouseImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lift Off Distance 的本地化字符串。
        /// </summary>
        internal static string MouseLiftOffDistance {
            get {
                return ResourceManager.GetString("MouseLiftOffDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Battery Warning at 的本地化字符串。
        /// </summary>
        internal static string MouseLowBatteryWarning {
            get {
                return ResourceManager.GetString("MouseLowBatteryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance 的本地化字符串。
        /// </summary>
        internal static string MousePerformance {
            get {
                return ResourceManager.GetString("MousePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synchronize with mouse 的本地化字符串。
        /// </summary>
        internal static string MouseSynchronize {
            get {
                return ResourceManager.GetString("MouseSynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi Zone 的本地化字符串。
        /// </summary>
        internal static string Multizone {
            get {
                return ResourceManager.GetString("Multizone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi Zone Strong 的本地化字符串。
        /// </summary>
        internal static string MultizoneStrong {
            get {
                return ResourceManager.GetString("MultizoneStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Muted 的本地化字符串。
        /// </summary>
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mute Mic 的本地化字符串。
        /// </summary>
        internal static string MuteMic {
            get {
                return ResourceManager.GetString("MuteMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never 的本地化字符串。
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New updates 的本地化字符串。
        /// </summary>
        internal static string NewUpdates {
            get {
                return ResourceManager.GetString("NewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No new updates 的本地化字符串。
        /// </summary>
        internal static string NoNewUpdates {
            get {
                return ResourceManager.GetString("NoNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Connected 的本地化字符串。
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumLock Off 的本地化字符串。
        /// </summary>
        internal static string NumLockOff {
            get {
                return ResourceManager.GetString("NumLockOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumLock On 的本地化字符串。
        /// </summary>
        internal static string NumLockOn {
            get {
                return ResourceManager.GetString("NumLockOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One Zone 的本地化字符串。
        /// </summary>
        internal static string OneZone {
            get {
                return ResourceManager.GetString("OneZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open G-Helper window 的本地化字符串。
        /// </summary>
        internal static string OpenGHelper {
            get {
                return ResourceManager.GetString("OpenGHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optimized 的本地化字符串。
        /// </summary>
        internal static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to Eco on battery and to Standard when plugged in 的本地化字符串。
        /// </summary>
        internal static string OptimizedGPUTooltip {
            get {
                return ResourceManager.GetString("OptimizedGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep GPU disabled on USB-C charger in Optimized mode 的本地化字符串。
        /// </summary>
        internal static string OptimizedUSBC {
            get {
                return ResourceManager.GetString("OptimizedUSBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overdrive 的本地化字符串。
        /// </summary>
        internal static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peripherals 的本地化字符串。
        /// </summary>
        internal static string Peripherals {
            get {
                return ResourceManager.GetString("Peripherals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Picture / Gif 的本地化字符串。
        /// </summary>
        internal static string PictureGif {
            get {
                return ResourceManager.GetString("PictureGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play / Pause 的本地化字符串。
        /// </summary>
        internal static string PlayPause {
            get {
                return ResourceManager.GetString("PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polling Rate 的本地化字符串。
        /// </summary>
        internal static string PollingRate {
            get {
                return ResourceManager.GetString("PollingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Limits 的本地化字符串。
        /// </summary>
        internal static string PowerLimits {
            get {
                return ResourceManager.GetString("PowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Limits is an experimental feature. Use carefully and at your own risk! 的本地化字符串。
        /// </summary>
        internal static string PPTExperimental {
            get {
                return ResourceManager.GetString("PPTExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintScreen 的本地化字符串。
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile 的本地化字符串。
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Something is using dGPU and preventing Eco mode. Let G-Helper try to restart dGPU in device manager? (Please proceed at your own risk) 的本地化字符串。
        /// </summary>
        internal static string RestartGPU {
            get {
                return ResourceManager.GetString("RestartGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPM 的本地化字符串。
        /// </summary>
        internal static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Stick Deadzones 的本地化字符串。
        /// </summary>
        internal static string RSDeadzones {
            get {
                return ResourceManager.GetString("RSDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Trigger Deadzones 的本地化字符串。
        /// </summary>
        internal static string RTDeadzones {
            get {
                return ResourceManager.GetString("RTDeadzones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run on Startup 的本地化字符串。
        /// </summary>
        internal static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scaling Quality 的本地化字符串。
        /// </summary>
        internal static string ScalingQuality {
            get {
                return ResourceManager.GetString("ScalingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenpad Brightness Down 的本地化字符串。
        /// </summary>
        internal static string ScreenPadDown {
            get {
                return ResourceManager.GetString("ScreenPadDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screenpad Brightness Up 的本地化字符串。
        /// </summary>
        internal static string ScreenPadUp {
            get {
                return ResourceManager.GetString("ScreenPadUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shutdown 的本地化字符串。
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silent 的本地化字符串。
        /// </summary>
        internal static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battery Level 的本地化字符串。
        /// </summary>
        internal static string SlashBatteryLevel {
            get {
                return ResourceManager.GetString("SlashBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bit Stream 的本地化字符串。
        /// </summary>
        internal static string SlashBitStream {
            get {
                return ResourceManager.GetString("SlashBitStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bounce 的本地化字符串。
        /// </summary>
        internal static string SlashBounce {
            get {
                return ResourceManager.GetString("SlashBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buzzer 的本地化字符串。
        /// </summary>
        internal static string SlashBuzzer {
            get {
                return ResourceManager.GetString("SlashBuzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        internal static string SlashFlow {
            get {
                return ResourceManager.GetString("SlashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flux 的本地化字符串。
        /// </summary>
        internal static string SlashFlux {
            get {
                return ResourceManager.GetString("SlashFlux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Over 的本地化字符串。
        /// </summary>
        internal static string SlashGameOver {
            get {
                return ResourceManager.GetString("SlashGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hazard 的本地化字符串。
        /// </summary>
        internal static string SlashHazard {
            get {
                return ResourceManager.GetString("SlashHazard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interfacing 的本地化字符串。
        /// </summary>
        internal static string SlashInterfacing {
            get {
                return ResourceManager.GetString("SlashInterfacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string SlashLoading {
            get {
                return ResourceManager.GetString("SlashLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slash 的本地化字符串。
        /// </summary>
        internal static string SlashMode {
            get {
                return ResourceManager.GetString("SlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phantom 的本地化字符串。
        /// </summary>
        internal static string SlashPhantom {
            get {
                return ResourceManager.GetString("SlashPhantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ramp 的本地化字符串。
        /// </summary>
        internal static string SlashRamp {
            get {
                return ResourceManager.GetString("SlashRamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spectrum 的本地化字符串。
        /// </summary>
        internal static string SlashSpectrum {
            get {
                return ResourceManager.GetString("SlashSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string SlashStart {
            get {
                return ResourceManager.GetString("SlashStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        internal static string SlashStatic {
            get {
                return ResourceManager.GetString("SlashStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transmission 的本地化字符串。
        /// </summary>
        internal static string SlashTransmission {
            get {
                return ResourceManager.GetString("SlashTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sleep 的本地化字符串。
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enables dGPU for standard use 的本地化字符串。
        /// </summary>
        internal static string StandardGPUTooltip {
            get {
                return ResourceManager.GetString("StandardGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string StandardMode {
            get {
                return ResourceManager.GetString("StandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting Services 的本地化字符串。
        /// </summary>
        internal static string StartingServices {
            get {
                return ResourceManager.GetString("StartingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup Error 的本地化字符串。
        /// </summary>
        internal static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop GPU Applications 的本地化字符串。
        /// </summary>
        internal static string StopGPUApps {
            get {
                return ResourceManager.GetString("StopGPUApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stopping Services 的本地化字符串。
        /// </summary>
        internal static string StoppingServices {
            get {
                return ResourceManager.GetString("StoppingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Aura 的本地化字符串。
        /// </summary>
        internal static string ToggleAura {
            get {
                return ResourceManager.GetString("ToggleAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Toggle Clamshell Mode 的本地化字符串。
        /// </summary>
        internal static string ToggleClamshellMode {
            get {
                return ResourceManager.GetString("ToggleClamshellMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Fn-Lock 的本地化字符串。
        /// </summary>
        internal static string ToggleFnLock {
            get {
                return ResourceManager.GetString("ToggleFnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Miniled (if supported) 的本地化字符串。
        /// </summary>
        internal static string ToggleMiniled {
            get {
                return ResourceManager.GetString("ToggleMiniled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Screen 的本地化字符串。
        /// </summary>
        internal static string ToggleScreen {
            get {
                return ResourceManager.GetString("ToggleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Touchscreen 的本地化字符串。
        /// </summary>
        internal static string ToggleTouchscreen {
            get {
                return ResourceManager.GetString("ToggleTouchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Touchscreen 的本地化字符串。
        /// </summary>
        internal static string Touchscreen {
            get {
                return ResourceManager.GetString("Touchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turbo 的本地化字符串。
        /// </summary>
        internal static string Turbo {
            get {
                return ResourceManager.GetString("Turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turned off 的本地化字符串。
        /// </summary>
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable on battery 的本地化字符串。
        /// </summary>
        internal static string TurnOffOnBattery {
            get {
                return ResourceManager.GetString("TurnOffOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routes laptop screen to dGPU, maximizing FPS 的本地化字符串。
        /// </summary>
        internal static string UltimateGPUTooltip {
            get {
                return ResourceManager.GetString("UltimateGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ultimate 的本地化字符串。
        /// </summary>
        internal static string UltimateMode {
            get {
                return ResourceManager.GetString("UltimateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undervolting is an experimental and risky feature. If applied values are too low for your hardware, it can become unstable, shut down or cause data corruption. If you want to try - start from small values first, click Apply and test what works for you. 的本地化字符串。
        /// </summary>
        internal static string UndervoltingRisky {
            get {
                return ResourceManager.GetString("UndervoltingRisky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmuted 的本地化字符串。
        /// </summary>
        internal static string Unmuted {
            get {
                return ResourceManager.GetString("Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Updates 的本地化字符串。
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vibration Strength 的本地化字符串。
        /// </summary>
        internal static string VibrationStrength {
            get {
                return ResourceManager.GetString("VibrationStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Mode 的本地化字符串。
        /// </summary>
        internal static string VisualMode {
            get {
                return ResourceManager.GetString("VisualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Modes are not available when HDR is active 的本地化字符串。
        /// </summary>
        internal static string VisualModesHDR {
            get {
                return ResourceManager.GetString("VisualModesHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Modes are not available when laptop screen is off 的本地化字符串。
        /// </summary>
        internal static string VisualModesScreen {
            get {
                return ResourceManager.GetString("VisualModesScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Down 的本地化字符串。
        /// </summary>
        internal static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Mute 的本地化字符串。
        /// </summary>
        internal static string VolumeMute {
            get {
                return ResourceManager.GetString("VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Up 的本地化字符串。
        /// </summary>
        internal static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep app window always on top 的本地化字符串。
        /// </summary>
        internal static string WindowTop {
            get {
                return ResourceManager.GetString("WindowTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
